### PR TITLE
Dynamic background

### PR DESCRIPTION
**Pull request by terjanq**
image

### CODE REVIEW

**Comment by meiamsome** [comment]
Hey, sorry, I merged #8 as a usability tweak and that meant that this now have conflicts - they should be easy to resolve, though, and then I guess @shiffman can chose whether to merge tomorrow

**Comment by terjanq** [comment]
Also added `user-select: none` to prevent users from accidental selecting elements on the site.

**Comment by terjanq** [comment]
Demo preview: https://terjanq.github.io/CrowdSourceColorData/

**Comment by terjanq** [comment]
Added last tweaks:
* better prevention from multiple clicks
* visual improvements
* removed outlines visible on the screenshot
* fixed logistic errors from source code

**Comment by Naahuel** [comment]
I like this. Makes the color in the canvas much more visible and clear.

**Comment by shiffman** [comment]
Ah, sorry, I merged things in reverse order and now there are conflicts! If you have time to take a look I'm happy to merge this!

**Comment by terjanq** [comment]
Done.

**Pull request merged**
